name: Nuke CICD Pipeline
on:
  push:
    branches:
    - prerelease
    - master
    tags:
    - bump-*
  pull_request:
    branches:
    - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  PRE_SETUP:
    name: Pre Setup
    runs-on:
      labels: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: recursive
        persist-credentials: true
    - id: NUKE_RUN
      name: Run Nuke PipelinePreSetup
      run: chmod +x ./build.sh && ./build.sh PipelinePreSetup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 10
    outputs:
      NUKE_PRE_SETUP: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP }}
      NUKE_PRE_SETUP_OUTPUT_TEST_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_TEST_MATRIX }}
      NUKE_PRE_SETUP_OUTPUT_BUILD_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_BUILD_MATRIX }}
      NUKE_PRE_SETUP_OUTPUT_PUBLISH_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_PUBLISH_MATRIX }}
      NUKE_PRE_SETUP_RESTFULHELPERSTEST_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSTEST_CONDITION }}
      NUKE_PRE_SETUP_RESTFULHELPERSTEST_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSTEST_RUNS_ON }}
      NUKE_PRE_SETUP_RESTFULHELPERSTEST_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSTEST_RUN_SCRIPT }}
      NUKE_PRE_SETUP_RESTFULHELPERSTEST_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSTEST_CACHE_KEY }}
      NUKE_PRE_SETUP_RESTFULHELPERSTEST_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSTEST_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_RESTFULHELPERSTEST_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSTEST_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_RESTFULHELPERSTEST_CHECKOUT_FETCH_DEPTH: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSTEST_CHECKOUT_FETCH_DEPTH }}
      NUKE_PRE_SETUP_RESTFULHELPERSTEST_CHECKOUT_FETCH_TAGS: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSTEST_CHECKOUT_FETCH_TAGS }}
      NUKE_PRE_SETUP_RESTFULHELPERSTEST_CHECKOUT_SUBMODULES: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSTEST_CHECKOUT_SUBMODULES }}
      NUKE_PRE_SETUP_RESTFULHELPERSBUILD_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSBUILD_CONDITION }}
      NUKE_PRE_SETUP_RESTFULHELPERSBUILD_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSBUILD_RUNS_ON }}
      NUKE_PRE_SETUP_RESTFULHELPERSBUILD_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSBUILD_RUN_SCRIPT }}
      NUKE_PRE_SETUP_RESTFULHELPERSBUILD_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSBUILD_CACHE_KEY }}
      NUKE_PRE_SETUP_RESTFULHELPERSBUILD_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSBUILD_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_RESTFULHELPERSBUILD_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSBUILD_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_RESTFULHELPERSBUILD_CHECKOUT_FETCH_DEPTH: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSBUILD_CHECKOUT_FETCH_DEPTH }}
      NUKE_PRE_SETUP_RESTFULHELPERSBUILD_CHECKOUT_FETCH_TAGS: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSBUILD_CHECKOUT_FETCH_TAGS }}
      NUKE_PRE_SETUP_RESTFULHELPERSBUILD_CHECKOUT_SUBMODULES: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSBUILD_CHECKOUT_SUBMODULES }}
      NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_CONDITION }}
      NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_RUNS_ON }}
      NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_RUN_SCRIPT }}
      NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_CACHE_KEY }}
      NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_CHECKOUT_FETCH_DEPTH: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_CHECKOUT_FETCH_DEPTH }}
      NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_CHECKOUT_FETCH_TAGS: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_CHECKOUT_FETCH_TAGS }}
      NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_CHECKOUT_SUBMODULES: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_CHECKOUT_SUBMODULES }}
  RESTFULHELPERSBUILD:
    name: Build - restful_helpers (RestfulHelpersBuild)
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSBUILD_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSBUILD_CHECKOUT_FETCH_DEPTH }}
        fetch-tags: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSBUILD_CHECKOUT_FETCH_TAGS }}
        submodules: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSBUILD_CHECKOUT_SUBMODULES }}
        persist-credentials: true
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/temp/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSBUILD_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSBUILD_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSBUILD_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke PipelineRunEntry
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSBUILD_RUN_SCRIPT }} PipelineRunEntry --args "run=build;idsToRun=RestfulHelpersBuild"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build___restful_helpers___RESTFULHELPERSBUILD
        path: ./.nuke/temp/artifacts-upload/*
        if-no-files-found: error
        retention-days: 1
    needs:
    - PRE_SETUP
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSBUILD_CONDITION == 'true'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  RESTFULHELPERSTEST:
    name: Test - restful_helpers (RestfulHelpersTest)
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSTEST_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSTEST_CHECKOUT_FETCH_DEPTH }}
        fetch-tags: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSTEST_CHECKOUT_FETCH_TAGS }}
        submodules: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSTEST_CHECKOUT_SUBMODULES }}
        persist-credentials: true
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts-download
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/temp/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSTEST_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSTEST_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSTEST_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke PipelineRunEntry
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSTEST_RUN_SCRIPT }} PipelineRunEntry --args "run=test;idsToRun=RestfulHelpersTest"
    needs:
    - PRE_SETUP
    - RESTFULHELPERSBUILD
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSTEST_CONDITION == 'true' && needs.RESTFULHELPERSBUILD.result == 'success'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  RESTFULHELPERSPUBLISH:
    name: Publish - restful_helpers (RestfulHelpersPublish)
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_CHECKOUT_FETCH_DEPTH }}
        fetch-tags: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_CHECKOUT_FETCH_TAGS }}
        submodules: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_CHECKOUT_SUBMODULES }}
        persist-credentials: true
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts-download
        pattern: build___restful_helpers___*
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/temp/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke PipelineRunEntry
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_RUN_SCRIPT }} PipelineRunEntry --args "run=publish;idsToRun=RestfulHelpersPublish"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: publish___restful_helpers___RESTFULHELPERSPUBLISH
        path: ./.nuke/temp/artifacts-upload/*
        if-no-files-found: error
        retention-days: 1
    needs:
    - PRE_SETUP
    - RESTFULHELPERSBUILD
    - RESTFULHELPERSTEST
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_RESTFULHELPERSPUBLISH_CONDITION == 'true' && needs.RESTFULHELPERSBUILD.result == 'success' && needs.RESTFULHELPERSTEST.result == 'success'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  POST_SETUP:
    name: Post Setup
    runs-on:
      labels: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: recursive
        persist-credentials: true
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts-download
        pattern: publish___*
    - name: Run Nuke PipelinePostSetup
      run: chmod +x ./build.sh && ./build.sh PipelinePostSetup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs:
    - PRE_SETUP
    - RESTFULHELPERSBUILD
    - RESTFULHELPERSTEST
    - RESTFULHELPERSPUBLISH
    if: success() || failure() || always()
    timeout-minutes: 10
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
      NUKE_RUN_RESULT_GITHUB_RESTFULHELPERSTEST: ${{ needs.RESTFULHELPERSTEST.result }}
      NUKE_RUN_RESULT_GITHUB_RESTFULHELPERSBUILD: ${{ needs.RESTFULHELPERSBUILD.result }}
      NUKE_RUN_RESULT_GITHUB_RESTFULHELPERSPUBLISH: ${{ needs.RESTFULHELPERSPUBLISH.result }}
env:
  NUKE_NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
  NUKE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
